# Generated by Django 3.2.7 on 2021-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulances',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('fare', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('userId', models.IntegerField(editable=False)),
                ('hospitalId', models.IntegerField(default=int, editable=False)),
                ('bookingType', models.CharField(max_length=30)),
                ('bookingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingsType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('bookingType', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CovidCentres',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
                ('availability', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('bedType', models.CharField(max_length=30)),
                ('availability', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('testType', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('supplyType', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(default=str, max_length=25)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=13)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('vaccineCost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('duration', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
