# Generated by Django 3.2.7 on 2021-09-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('vaccineCost', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='vaccinetype',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
