# Generated by Django 3.2.7 on 2021-10-26 04:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bookingType', models.CharField(max_length=30)),
                ('bookingDate', models.DateField()),
            ],
        ),
    ]
