# Generated by Django 3.2.7 on 2021-10-26 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='hospitalId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
