# Generated by Django 3.2.7 on 2021-10-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_users_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCareCentres',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('testType', models.CharField(max_length=30)),
                ('cost', models.IntegerField(default=int)),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CovidTestingLabs',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
                ('availability', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='CovidCentres',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='VaccineCentre',
        ),
        migrations.DeleteModel(
            name='VaccineType',
        ),
    ]
