# Generated by Django 3.2.7 on 2021-10-26 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_bookings_hospitalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingsType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bookingType', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
